foundation: "MEC Landscape"
url: "https://ai-eddy.github.io/my-landscape"   # ohne trailing slash
base_path: "/my-landscape"                      # mit f√ºhrendem Slash
title: "MEC Landscape"
description: "Eigene Landscape mit landscape2"
grid_items_size: large
header:
  links:
    github: https://github.com/AI-Eddy/my-landscape
  logo: my-landscape/5GMEC4EU_Logo.svg



